### PR TITLE
First draft convert repronim-containers tutorial for website

### PR DESCRIPTION
**Pull request by asmacdo**
Heres my first draft of the tutorial, taken mostly verbatim from the https://github.com/ReproNim/containers/README.md

@memartone does this conform to the layout you are looking for? 
(Use the netlify bot comment below to get the latest preview)

TODO before merge
- [ ] asmacdo to review and run all steps to ensure accuracy

### CODE REVIEW

**Comment by chaselgrove** [comment]
@asmacdo please include a "before you start" section listing assumed knowledge (and how to get it).  The DICOM to BIDS tutorial has a nice example of that.

**Comment by asmacdo** [comment]
@chaselgrove thank you, added in latest push.

**Comment by chaselgrove** [comment]
@asmacdo looks good; thanks.

**Comment by chaselgrove** [comment]
I wouldn't worry too much about the accuracy of the commands.  (The EAB won't! :) )

**Comment by chaselgrove** [comment]
Resolves #82

**Comment by asmacdo** [comment]
The tutorial was broken by a recent update to repronim/containers. https://github.com/ReproNim/containers/issues/135

 I didn't have a quickfix so lets merge as-is, and Ill file an issue here to update when the upstream tutorial is fixed.

**Pull request merged**
